- name: Install nginx
  apt: >
    package={{ item }} 
    state=latest
    force=yes 
    update_cache=yes 
    cache_valid_time=3600
  when: ansible_os_family == 'Debian'
  with_items:
    - nginx
  become: true

- name: Update default Nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  become: true
  notify:
    - restart nginx

# https://www.linode.com/docs/web-servers/nginx/use-nginx-reverse-proxy/#basic-configuration-for-an-nginx-reverse-proxy
- name: Setup Nginx as reverse proxy
  template:
    src: veryfy_api.conf.j2
    dest: /etc/nginx/conf.d/veryfy_api.conf
  become: true
  notify:
    - restart nginx
