---
- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: latest
    force: yes
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev
  become: true
