---
- name: rehash
  raw: 'RBENV_ROOT={{ rbenv_path }} {{ rbenv_path }}/bin/rbenv rehash'
  become: true

- name: set Global ruby
  raw: 'RBENV_ROOT={{ rbenv_path }} {{ rbenv_path }}/bin/rbenv global {{ ruby_version }}'
  become: true
