---
- name: Setup before gathering facts.
  hosts: minio
  gather_facts: no
  roles:
    - setup

- name: Provision minio object store.
  hosts: minio
  roles:
    - nginx
    - role: atosatto.minio
      vars:
        minio_access_key: "{{ minio_access_key }}"
        minio_secret_key: "{{ minio_secret_key }}"
        minio_server_datadirs: ["/minio-store"]
        minio_install_client: false
