---
- name: Setup before gathering facts
  hosts: production_server
  gather_facts: no

  roles:
    - setup

- name: Configure Server for Rails app
  hosts: production_server

  roles:
    - create-deploy-user    
    - rails-config
    - nginx
    - { role: mysql, when: mysql_setup == true }
    - postgres
    - rbenv