---
- name: Setup before gathering facts.
 hosts: production
  gather_facts: no
  roles:
    - setup

- name: Provision a production server for veryfy api.
 hosts: production
  roles:
    - nginx
    - redis
    - rails-config
    - rbenv
    - role: weareinteractive.environment
      vars:
        environment_config:
          PATH: "/usr/local/rbenv/shims:/usr/local/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
      become: yes
      become_user: root
