---
- name: Setup before gathering facts
  hosts: server_setup
  gather_facts: no

  roles:
    - setup

- name: Configure Server for Rails app
  hosts: server_setup

  roles:
    - create-deploy-user    
    - rails-config