---
- name: Setup before gathering facts
  hosts: '{{ app_env }}'
  gather_facts: no

  roles:
    - setup

- name: Configure Server for Rails app
  hosts: '{{ app_env }}'

  roles:
    - create-deploy-user
    - rails-config
    - nginx
    - { role: mysql, when: mysql_setup == true }
    - { role: postgres, when: postgres_setup == true }
    - rbenv
    - redis
