---
- name: Setup before gathering facts
  hosts: "{{ app_env }}"
  gather_facts: no
  roles:
    - setup

- name: Configure Server for Veryfy_2.0 API
  hosts: "{{ app_env }}"
  roles:
    # - rails-config
    - nginx
    # - {
    #     role: postgres,
    #     when: postgres_setup == true,
    #     pg_user: "veryfy",
    #     pg_user_password: "{{ pg_user_pass }}",
    #   }
    # - rbenv
    # - redis
    # - role: weareinteractive.environment
    #   vars:
    #     environment_config:
    #       PATH: "/usr/local/rbenv/shims:/usr/local/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
    #   become: yes
    #   become_user: root
    # - role: atosatto.minio
    #   vars:
    #     minio_access_key: "{{ minio_access_key }}"
    #     minio_secret_key: "{{ minio_secret_key }}"
    #     minio_server_datadirs: ["/minio-store"]
    #     minio_install_client: false
