---
- name: Setup before gathering facts.
  hosts: staging
  gather_facts: no
  roles:
    - setup

- name: Provision a staging server for veryfy api.
  hosts: staging
  roles:
    - nginx
    - redis
    - role: postgres
      vars:
        pg_user: "veryfy"
        pg_user_password: "{{ pg_user_pass }}"
    - rails-config
    - rbenv
    - role: weareinteractive.environment
    vars:
      environment_config:
        PATH: "/usr/local/rbenv/shims:/usr/local/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
    become: yes
    become_user: root
    - role: elastic.elasticsearch
      vars:
        es_data_dirs:
          - "/opt/elasticsearch/data"
        es_log_dir: "/opt/elasticsearch/logs"
        es_config:
          node.name: "staging"
          http.port: 9200
          node.data: false
          node.master: true
          bootstrap.memory_lock: true
        es_heap_size: 1g
