---
- name: Setup before gathering facts.
  hosts: staging
  gather_facts: no
  roles:
    - setup

- name: Provision a staging server for veryfy frontend.
  hosts: staging
  roles:
    - nginx
    - role: weareinteractive.environment
      vars:
        environment_config:
          PATH: "/usr/local/rbenv/shims:/usr/local/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
      become: yes
      become_user: root
