- name: Delete anonymous MySQL server user for localhost
  mysql_user: >
    user={{ item }}
    state=absent
    login_password={{ mysql_root_password }}
    login_user=root
  with_items:
    - ''

- name: Removes the MySQL test database
  mysql_db: >
    db=test
    state=absent
    login_password={{ mysql_root_password }}
    login_user=root