---
- name: Secures the Mysql root user
  mysql_user: >
    user=root
    password={{ mysql_root_password }}
    host={{ item }}
    login_password={{ mysql_root_password }}
    login_user=root
  with_items:
    - 127.0.0.1
    - localhost
    - ::1
    - "{{ ansible_fqdn }}"  

- name: Create MySQL server user for localhost
  mysql_user: >
    user={{ item }}
    password={{ mysql_user_password }}
    priv='*.*:ALL,GRANT'
    state=present
    login_password={{ mysql_root_password }}
    login_user=root
  with_items:
    - "{{ mysql_user }}"    