---
- name: Install Mysql
  apt: >
    package={{ item }}
    state=installed
    force=yes
    update_cache=yes
    cache_valid_time=3600
  when: ansible_os_family == 'Debian'
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb
  become: true  

- name: Create Mysql configuration file
  template:
    src=my.cnf.j2
    dest=/etc/my.cnf
  become: true
  notify:
    - restart mysql  