- name: Set mysql root password before installing
  debconf: >
    name='mysql-server'
    question='mysql-server/root_password'
    value='{{mysql_root_password | quote}}'
    vtype='password'
  become: true

- name: Confirm mysql root password before installing
  debconf: >
    name='mysql-server'
    question='mysql-server/root_password_again'
    value='{{mysql_root_password | quote}}'
    vtype='password'
  become: true

- name: Install Mysql
  apt: >
    package={{ item }}
    state=installed
    force=yes
    update_cache=yes
    cache_valid_time=3600
  when: ansible_os_family == 'Debian'
  with_items:
    - mysql-server
    - mysql-client
  become: true  

- name: Secures the Mysql root user
  mysql_user: >
    user=root
    password={{ mysql_root_password }}
    host={{ item }}
    login_password={{ mysql_root_password }}
    login_user=root
  with_items:
    - 127.0.0.1
    - localhost
    - ::1
    - "{{ ansible_fqdn }}"  

- name: Delete anonymous MySQL server user for localhost
  mysql_user: >
    user={{ item }}
    state=absent
    login_password={{ mysql_root_password }}
    login_user=root
  with_items:
    - ''

- name: Removes the MySQL test database
  mysql_db: >
    db=test
    state=absent
    login_password={{ mysql_root_password }}
    login_user=root

- name: Create MySQL server user for localhost
  mysql_user: >
    user={{ item }}
    password={{ mysql_user_password }}
    priv='*.*:ALL,GRANT'
    state=present
    login_password={{ mysql_root_password }}
    login_user=root
  with_items:
    - "{{ mysql_user }}"

                