- name: Set mysql root password before installing
  debconf: >
    name='mysql-server'
    question='mysql-server/root_password'
    value='{{mysql_root_password | quote}}'
    vtype='password'
  become: true

- name: Confirm mysql root password before installing
  debconf: >
    name='mysql-server'
    question='mysql-server/root_password_again'
    value='{{mysql_root_password | quote}}'
    vtype='password'
  become: true

- name: Install Mysql
  apt: >
    package={{ item }}
    state=installed
    force=yes
    update_cache=yes
    cache_valid_time=3600
  when: ansible_os_family == 'Debian'
  with_items:
    - mysql-server
    - mysql-client
  become: true  