- name: Create deployment user
  user: name={{ deploy_user }} comment="Application deployment user"
  become: true

- name: Update user permissions
  template:
    src: templates/deployer.j2
    dest: /etc/sudoers.d/deployer
    owner: root
    group: root
    mode: 0440
  become: true    

- name: Create .ssh folder
  file:
    path: '/home/{{ deploy_user }}/.ssh'  
    state: directory
    group: '{{ deploy_user }}'
    owner: '{{ deploy_user }}'
  become: true

- name: "Update {{ deploy_user }}'s allowed keys"
  copy:
    remote_src: true
    src: /home/{{ remote_user }}/.ssh/id_rsa
    dest: /home/{{ deploy_user }}/.ssh/id_rsa
    group: '{{ deploy_user }}'
    owner: '{{ deploy_user }}'
  become: true
