---
- name: Check for ruby version {{ ruby_version }}
  stat:
    path: '{{ rbenv_path }}/versions/{{ ruby_version }}'
  register: ruby
  ignore_errors: yes

- block:
  - name: Install ruby {{ ruby_version }}
    raw: 'RBENV_ROOT={{ rbenv_path }} {{ rbenv_path }}/bin/rbenv install {{ ruby_version }}'
    become: true

  - name: Rehash ruby installations
    raw: 'RBENV_ROOT={{ rbenv_path }} {{ rbenv_path }}/bin/rbenv rehash'
    become: true

  when: ruby.stat.exists == false
