---
- name: Check for previous versin rbenv
  stat:
    path: '{{ rbenv_path }}/bin/rbenv'
  ignore_errors: true
  register: rbenv_bin_dir

- block:
  - name: Create rbenv base directory
    file:
      path: '{{ rbenv_path }}'
      state: directory
      group: '{{ remote_user }}'
      owner: '{{ remote_user }}'  
    become: true  

  - name: git clone rbenv
    git:
      repo: '{{ rbenv_url }}'
      dest: '{{ rbenv_path }}'
      accept_hostkey: yes  

  - name: Add rbenv bash config to PATH
    template:
      src: rbenv.sh.j2
      dest: /etc/profile.d/rbenv.sh
      owner: root
      group: root
      mode: 0775
    become: true    
  when: rbenv_bin_dir.stat.exists == false
