---
- name: Create postgres user for app database
  postgresql_db:
    name: '{{ app_name }}_{{ app_env }}'
    state: present
  become_user: postgres
  become: true

- name: Ensure user {{ postgres_user }} exists
  postgresql_user:
    db: '{{ app_name }}_{{ app_env }}'
    name: '{{ postgres_user }}'
    password: '{{ postgres_password }}'
    priv: "ALL"
    state: present
    encrypted: true
  become_user: postgres
  become: true
