---
- name: Install Postgres
  apt: >
    package={{ item }}
    state=latest
    force=yes
    update_cache=yes
    cache_valid_time=3600
  when: ansible_os_family == 'Debian'
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
    - python3-psycopg2
  become: true
