---
- include: install-postgres.yml

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- include: create-user.yml
  notify:
    - restart postgresql
  become: true
